### ISSUE TITLE
点击扫描崩溃

### ISSUE THREAD

**Issue by zhou9527** [465857721/IDCardOCR_China#1]
Caused by: java.lang.IllegalArgumentException: Data file not found at /storage/emulated/0/ayy/tessdata/eng.traineddata
                                                                                  at com.googlecode.tesseract.android.TessBaseAPI.init(TessBaseAPI.java:320)
                                                                                  at com.googlecode.tesseract.android.TessBaseAPI.init(TessBaseAPI.java:284)
                                                                                  at com.kingsoft.idcardocr_china.idcardocr.CameraActivity.onCreate(CameraActivity.java:61)

**Comment by 465857721** [comment]
权限问题没有处理，打开文件读写权限

**Comment by wangyangke** [comment]
您好，我QQ是522279122，请加下我，有问题请教您
